# Generated by Django 6.0.6 on 2026-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='onec_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='1C Ид'),
        ),
        migrations.AddField(
            model_name='product',
            name='onec_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='1C Ид'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='onec_id',
            field=models.CharField(blank=True, db_index=True, max_length=130, verbose_name='1C Ид'),
        ),
    ]
