# Generated by Django 6.0.6 on 2026-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneCExchangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('catalog', 'Kataloq (import.xml)'), ('offers', 'Təkliflər / qiymət-stok (offers.xml)'), ('sale', 'Sifarişlər'), ('other', 'Digər')], default='other', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '1C exchange log',
                'verbose_name_plural': '1C exchange logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
